### ISSUE TITLE
联想签到脚本失效

### ISSUE THREAD

**Issue by onlyLTY** [OreosLab/checkinpanel#146]
## 开始执行... 2022-08-17 09:21:07

🔔联想商城, 开始!

🔔sendNotify, 开始!
account 数量：2

======== [Account 1] Start ======== 
登录成功！
获取token失败 请升级App版本

======== [Account 2] Start ======== 
登录成功！
获取token失败 请升级App版本
server酱 发送通知消息成功🎉

## 执行结束... 2022-08-17 09:21:13 耗时 6 秒

**Comment by thinker226** [comment]
是的  同样碰到这个情况

**Comment by Amongsterdevil** [comment]
首先要确保 alt+makes 的方式和协议的一方必须遵循另一个类似

**Comment by onlyLTY** [comment]
> 

能细说吗

**Comment by Oreomeow** [comment]
已修复

**Comment by onlyLTY** [comment]
> 已修复

多账号下第二个账号无法签到

======== [Account 1] Start ======== 
登录成功！
今天已经签到过啦

======== [Account 2] Start ======== 
登录成功！
获取token失败 请升级App版本
server酱 发送通知消息成功🎉
