### ISSUE TITLE
联想签到脚本多账号签到失败

### ISSUE THREAD

**Issue by onlyLTY** [OreosLab/checkinpanel#163]
尝试过对调账号。结果依然只有账号1可以签到，账号2无法签到。只有放在account1的才能签上
======== [Account 1] Start ======== 
登录成功！
今天已经签到过啦

======== [Account 2] Start ======== 
登录成功！
获取token失败 请升级App版本
server酱 发送通知消息成功🎉

**Comment by Oreomeow** [comment]
@onlyLTY 晚点修

**Comment by Oreomeow** [comment]
@onlyLTY 已修复
